#!/bin/sh
# Run a test manually
# Copyright (C) 1998 Free Software Foundation, Inc.

srcdir=.
export srcdir

shopts=
test -z "$VERBOSE" || shopts=-x

if sh $shopts "$@"; then
    echo "Test succeeded"
else
    echo "TEST FAILED"

    if cmp testSubDir/ok testSubDir/out 2>/dev/null; then
	:
    else
	echo "stdout mismatch"
	diff -c  testSubDir/ok testSubDir/out
    fi

    if test -e testSubDir/err; then
	if cmp testSubDir/okerr testSubDir/err 2>/dev/null; then
	    :
	else
	    echo "stderr mismatch"
	    diff -c  testSubDir/okerr testSubDir/err
	fi
    fi
fi
